import axios from "axios";
import { WITHDRAW_AMOUNT } from "../constants/define";
import { SuccessResponse } from "../core/ApiResponse";
import asyncHandler from "../helpers/asyncHandler";
import { PublicRequest } from "../types/app-request";
import { ConfigModel } from "../database/model/Config";
import _ from "lodash";

const getRateUsd = async () => {
  const res = await axios.get(
    "https://api.coingecko.com/api/v3/simple/price?ids=tether&vs_currencies=vnd"
  );
  return res?.data?.tether?.vnd || 0;
};

export const farmVip: Record<
  number,
  {
    profitPercent: number;
    activityPlus: number;
    totalDep: number;
  }
> = {
  1: {
    profitPercent: 0.5,
    activityPlus: 1,
    totalDep: 20,
  },
  2: {
    profitPercent: 0.8,
    activityPlus: 1,
    totalDep: 100,
  },
  3: {
    profitPercent: 1.5,
    activityPlus: 2,
    totalDep: 300,
  },
  4: {
    profitPercent: 2,
    activityPlus: 2,
    totalDep: 500,
  },
  5: {
    profitPercent: 3,
    activityPlus: 5,
    totalDep: 1000,
  },
};

export const blackBlist = [100]; //52709
export const bankList = [
  {
    id: 17,
    name: "Ngân hàng TMCP Công thương Việt Nam",
    code: "ICB",
    bin: "970415",
    shortName: "VietinBank",
    logo: "https://api.vietqr.io/img/ICB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietinBank",
    support: 3,
    isTransfer: 1,
    swift_code: "ICBVVNVX",
  },
  {
    id: 43,
    name: "Ngân hàng TMCP Ngoại Thương Việt Nam",
    code: "VCB",
    bin: "970436",
    shortName: "Vietcombank",
    logo: "https://api.vietqr.io/img/VCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Vietcombank",
    support: 3,
    isTransfer: 1,
    swift_code: "BFTVVNVX",
  },
  {
    id: 4,
    name: "Ngân hàng TMCP Đầu tư và Phát triển Việt Nam",
    code: "BIDV",
    bin: "970418",
    shortName: "BIDV",
    logo: "https://api.vietqr.io/img/BIDV.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BIDV",
    support: 3,
    isTransfer: 1,
    swift_code: "BIDVVNVX",
  },
  {
    id: 42,
    name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam",
    code: "VBA",
    bin: "970405",
    shortName: "Agribank",
    logo: "https://api.vietqr.io/img/VBA.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Agribank",
    support: 3,
    isTransfer: 1,
    swift_code: "VBAAVNVX",
  },
  {
    id: 26,
    name: "Ngân hàng TMCP Phương Đông",
    code: "OCB",
    bin: "970448",
    shortName: "OCB",
    logo: "https://api.vietqr.io/img/OCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "OCB",
    support: 3,
    isTransfer: 1,
    swift_code: "ORCOVNVX",
  },
  {
    id: 21,
    name: "Ngân hàng TMCP Quân đội",
    code: "MB",
    bin: "970422",
    shortName: "MBBank",
    logo: "https://api.vietqr.io/img/MB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "MBBank",
    support: 3,
    isTransfer: 1,
    swift_code: "MSCBVNVX",
  },
  {
    id: 38,
    name: "Ngân hàng TMCP Kỹ thương Việt Nam",
    code: "TCB",
    bin: "970407",
    shortName: "Techcombank",
    logo: "https://api.vietqr.io/img/TCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Techcombank",
    support: 3,
    isTransfer: 1,
    swift_code: "VTCBVNVX",
  },
  {
    id: 2,
    name: "Ngân hàng TMCP Á Châu",
    code: "ACB",
    bin: "970416",
    shortName: "ACB",
    logo: "https://api.vietqr.io/img/ACB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ACB",
    support: 3,
    isTransfer: 1,
    swift_code: "ASCBVNVX",
  },
  {
    id: 47,
    name: "Ngân hàng TMCP Việt Nam Thịnh Vượng",
    code: "VPB",
    bin: "970432",
    shortName: "VPBank",
    logo: "https://api.vietqr.io/img/VPB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VPBank",
    support: 3,
    isTransfer: 1,
    swift_code: "VPBKVNVX",
  },
  {
    id: 39,
    name: "Ngân hàng TMCP Tiên Phong",
    code: "TPB",
    bin: "970423",
    shortName: "TPBank",
    logo: "https://api.vietqr.io/img/TPB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "TPBank",
    support: 3,
    isTransfer: 1,
    swift_code: "TPBVVNVX",
  },
  {
    id: 36,
    name: "Ngân hàng TMCP Sài Gòn Thương Tín",
    code: "STB",
    bin: "970403",
    shortName: "Sacombank",
    logo: "https://api.vietqr.io/img/STB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Sacombank",
    support: 3,
    isTransfer: 1,
    swift_code: "SGTTVNVX",
  },
  {
    id: 12,
    name: "Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh",
    code: "HDB",
    bin: "970437",
    shortName: "HDBank",
    logo: "https://api.vietqr.io/img/HDB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "HDBank",
    support: 3,
    isTransfer: 1,
    swift_code: "HDBCVNVX",
  },
  {
    id: 44,
    name: "Ngân hàng TMCP Bản Việt",
    code: "VCCB",
    bin: "970454",
    shortName: "VietCapitalBank",
    logo: "https://api.vietqr.io/img/VCCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietCapitalBank",
    support: 3,
    isTransfer: 1,
    swift_code: "VCBCVNVX",
  },
  {
    id: 31,
    name: "Ngân hàng TMCP Sài Gòn",
    code: "SCB",
    bin: "970429",
    shortName: "SCB",
    logo: "https://api.vietqr.io/img/SCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SCB",
    support: 3,
    isTransfer: 1,
    swift_code: "SACLVNVX",
  },
  {
    id: 45,
    name: "Ngân hàng TMCP Quốc tế Việt Nam",
    code: "VIB",
    bin: "970441",
    shortName: "VIB",
    logo: "https://api.vietqr.io/img/VIB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VIB",
    support: 3,
    isTransfer: 1,
    swift_code: "VNIBVNVX",
  },
  {
    id: 35,
    name: "Ngân hàng TMCP Sài Gòn - Hà Nội",
    code: "SHB",
    bin: "970443",
    shortName: "SHB",
    logo: "https://api.vietqr.io/img/SHB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SHB",
    support: 3,
    isTransfer: 1,
    swift_code: "SHBAVNVX",
  },
  {
    id: 10,
    name: "Ngân hàng TMCP Xuất Nhập khẩu Việt Nam",
    code: "EIB",
    bin: "970431",
    shortName: "Eximbank",
    logo: "https://api.vietqr.io/img/EIB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Eximbank",
    support: 3,
    isTransfer: 1,
    swift_code: "EBVIVNVX",
  },
  {
    id: 22,
    name: "Ngân hàng TMCP Hàng Hải",
    code: "MSB",
    bin: "970426",
    shortName: "MSB",
    logo: "https://api.vietqr.io/img/MSB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "MSB",
    support: 3,
    isTransfer: 1,
    swift_code: "MCOBVNVX",
  },
  {
    id: 53,
    name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank",
    code: "CAKE",
    bin: "546034",
    shortName: "CAKE",
    logo: "https://api.vietqr.io/img/CAKE.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "CAKE",
    support: 3,
    isTransfer: 1,
    swift_code: null,
  },
  {
    id: 54,
    name: "TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank",
    code: "Ubank",
    bin: "546035",
    shortName: "Ubank",
    logo: "https://api.vietqr.io/img/UBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Ubank",
    support: 3,
    isTransfer: 1,
    swift_code: null,
  },

  {
    id: 34,
    name: "Ngân hàng TMCP Sài Gòn Công Thương",
    code: "SGICB",
    bin: "970400",
    shortName: "SaigonBank",
    logo: "https://api.vietqr.io/img/SGICB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SaigonBank",
    support: 3,
    isTransfer: 1,
    swift_code: "SBITVNVX",
  },
  {
    id: 3,
    name: "Ngân hàng TMCP Bắc Á",
    code: "BAB",
    bin: "970409",
    shortName: "BacABank",
    logo: "https://api.vietqr.io/img/BAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BacABank",
    support: 3,
    isTransfer: 1,
    swift_code: "NASCVNVX",
  },
  {
    id: 30,
    name: "Ngân hàng TMCP Đại Chúng Việt Nam",
    code: "PVCB",
    bin: "970412",
    shortName: "PVcomBank",
    logo: "https://api.vietqr.io/img/PVCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "PVcomBank",
    support: 3,
    isTransfer: 1,
    swift_code: "WBVNVNVX",
  },
  {
    id: 27,
    name: "Ngân hàng Thương mại TNHH MTV Đại Dương",
    code: "Oceanbank",
    bin: "970414",
    shortName: "Oceanbank",
    logo: "https://api.vietqr.io/img/OCEANBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Oceanbank",
    support: 3,
    isTransfer: 1,
    swift_code: "OCBKUS3M",
  },
  {
    id: 24,
    name: "Ngân hàng TMCP Quốc Dân",
    code: "NCB",
    bin: "970419",
    shortName: "NCB",
    logo: "https://api.vietqr.io/img/NCB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "NCB",
    support: 3,
    isTransfer: 1,
    swift_code: "NVBAVNVX",
  },
  {
    id: 37,
    name: "Ngân hàng TNHH MTV Shinhan Việt Nam",
    code: "SHBVN",
    bin: "970424",
    shortName: "ShinhanBank",
    logo: "https://api.vietqr.io/img/SHBVN.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ShinhanBank",
    support: 3,
    isTransfer: 1,
    swift_code: "SHBKVNVX",
  },
  {
    id: 1,
    name: "Ngân hàng TMCP An Bình",
    code: "ABB",
    bin: "970425",
    shortName: "ABBANK",
    logo: "https://api.vietqr.io/img/ABB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "ABBANK",
    support: 3,
    isTransfer: 1,
    swift_code: "ABBKVNVX",
  },
  {
    id: 41,
    name: "Ngân hàng TMCP Việt Á",
    code: "VAB",
    bin: "970427",
    shortName: "VietABank",
    logo: "https://api.vietqr.io/img/VAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietABank",
    support: 3,
    isTransfer: 1,
    swift_code: "VNACVNVX",
  },
  {
    id: 23,
    name: "Ngân hàng TMCP Nam Á",
    code: "NAB",
    bin: "970428",
    shortName: "NamABank",
    logo: "https://api.vietqr.io/img/NAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "NamABank",
    support: 3,
    isTransfer: 1,
    swift_code: "NAMAVNVX",
  },
  {
    id: 29,
    name: "Ngân hàng TMCP Xăng dầu Petrolimex",
    code: "PGB",
    bin: "970430",
    shortName: "PGBank",
    logo: "https://api.vietqr.io/img/PGB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "PGBank",
    support: 3,
    isTransfer: 1,
    swift_code: "PGBLVNVX",
  },
  {
    id: 46,
    name: "Ngân hàng TMCP Việt Nam Thương Tín",
    code: "VIETBANK",
    bin: "970433",
    shortName: "VietBank",
    logo: "https://api.vietqr.io/img/VIETBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "VietBank",
    support: 3,
    isTransfer: 1,
    swift_code: "VNTTVNVX",
  },
  {
    id: 5,
    name: "Ngân hàng TMCP Bảo Việt",
    code: "BVB",
    bin: "970438",
    shortName: "BaoVietBank",
    logo: "https://api.vietqr.io/img/BVB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "BaoVietBank",
    support: 3,
    isTransfer: 1,
    swift_code: "BVBVVNVX",
  },
  {
    id: 33,
    name: "Ngân hàng TMCP Đông Nam Á",
    code: "SEAB",
    bin: "970440",
    shortName: "SeABank",
    logo: "https://api.vietqr.io/img/SEAB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "SeABank",
    support: 3,
    isTransfer: 1,
    swift_code: "SEAVVNVX",
  },
  {
    id: 52,
    name: "Ngân hàng Hợp tác xã Việt Nam",
    code: "COOPBANK",
    bin: "970446",
    shortName: "COOPBANK",
    logo: "https://api.vietqr.io/img/COOPBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "COOPBANK",
    support: 3,
    isTransfer: 1,
    swift_code: null,
  },
  {
    id: 20,
    name: "Ngân hàng TMCP Lộc Phát Việt Nam",
    code: "LPB",
    bin: "970449",
    shortName: "LPBank",
    logo: "https://api.vietqr.io/img/LPB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "LPBank",
    support: 3,
    isTransfer: 1,
    swift_code: "LVBKVNVX",
  },
  {
    id: 19,
    name: "Ngân hàng TMCP Kiên Long",
    code: "KLB",
    bin: "970452",
    shortName: "KienLongBank",
    logo: "https://api.vietqr.io/img/KLB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "KienLongBank",
    support: 3,
    isTransfer: 1,
    swift_code: "KLBKVNVX",
  },
  {
    id: 55,
    name: "Ngân hàng Đại chúng TNHH Kasikornbank",
    code: "KBank",
    bin: "668888",
    shortName: "KBank",
    logo: "https://api.vietqr.io/img/KBANK.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "KBank",
    support: 3,
    isTransfer: 1,
    swift_code: "KASIVNVX",
  },

  {
    id: 49,
    name: "Ngân hàng TNHH MTV Woori Việt Nam",
    code: "WVN",
    bin: "970457",
    shortName: "Woori",
    logo: "https://api.vietqr.io/img/WVN.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "Woori",
    support: 0,
    isTransfer: 1,
    swift_code: null,
  },

  {
    id: 7,
    name: "Ngân hàng TNHH MTV CIMB Việt Nam",
    code: "CIMB",
    bin: "422589",
    shortName: "CIMB",
    logo: "https://api.vietqr.io/img/CIMB.png",
    transferSupported: 1,
    lookupSupported: 1,
    short_name: "CIMB",
    support: 0,
    isTransfer: 1,
    swift_code: "CIBBVNVN",
  },
  {
    id: 6,
    name: "Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam",
    code: "CBB",
    bin: "970444",
    shortName: "CBBank",
    logo: "https://api.vietqr.io/img/CBB.png",
    transferSupported: 0,
    lookupSupported: 1,
    short_name: "CBBank",
    support: 0,
    isTransfer: 0,
    swift_code: "GTBAVNVX",
  },
];
export const configVip = {
  vipReward: {
    reward_a: 8,
    reward_b: 3,
    reward_c: 1,
  },
  vipList: [
    {
      id: 2,
      lv: 1,
      invite_num: 5,
      dividend: 1,
      product_profit: 0.3,
      level_up_money: 5,
      wage: 2,
    },
    {
      id: 3,
      lv: 2,
      invite_num: 10,
      dividend: 2,
      product_profit: 0.6,
      level_up_money: 15,
      wage: 5,
    },
    {
      id: 4,
      lv: 3,
      invite_num: 20,
      dividend: 3,
      product_profit: 0.9,
      level_up_money: 40,
      wage: 10,
    },
    {
      id: 5,
      lv: 4,
      invite_num: 50,
      dividend: 4,
      product_profit: 1.2,
      level_up_money: 100,
      wage: 20,
    },
    {
      id: 6,
      lv: 5,
      invite_num: 100,
      dividend: 5,
      product_profit: 1.8,
      level_up_money: 200,
      wage: 50,
    },
    {
      id: 7,
      lv: 6,
      invite_num: 150,
      dividend: 6,
      product_profit: 2.1,
      level_up_money: 250,
      wage: 100,
    },
    {
      id: 8,
      lv: 7,
      invite_num: 200,
      dividend: 7,
      product_profit: 3,
      level_up_money: 350,
      wage: 150,
    },
    {
      id: 9,
      lv: 8,
      invite_num: 300,
      dividend: 8,
      product_profit: 3.5,
      level_up_money: 400,
      wage: 300,
    },
    {
      id: 10,
      lv: 9,
      invite_num: 500,
      dividend: 9,
      product_profit: 4,
      level_up_money: 500,
      wage: 500,
    },
  ],
};

export const commissionRate = 0.01;

export const checkIn = [0.05, 0.05, 0.1, 0.2, 0.2, 0.4, 0.5];

export default {
  getConfig: asyncHandler(async (req: PublicRequest, res) => {
    const configsCurrent = await ConfigModel.find();

    const configData = _.mapValues(
      _.keyBy(configsCurrent, "key"),
      "value"
    ) as any;

    const banking = configData?.PAYMENT_GATEWAY
      ? JSON.parse(configData?.PAYMENT_GATEWAY + "")
      : {};

    const rateUsd = Number(configData?.USDT_PRICE || 26000);
    return new SuccessResponse("ok", {
      ...configVip,
      ...configData,
      bankList,
      paymentGateWay: {
        crypto: {
          BEP20:
            configData?.BEP20_ADDRESS ||
            "0x951593b3cc55d003c8f550dc39086a625408f8db",
          imageQr: "/uploads/imageqr-bep20.jpg",
        },

        banking:
          // {
          //   holderName: "Nguyen Thanh Loc",
          //   nameBank: "Wooribank",
          //   numberBank: "100200475856",
          //   code: "WOORI",
          // },
          {
            ...banking,
          },
      },
      checkIn,
      timeDeposit: 1000 * 60 * 30,
      rateUsd,
      rateUsdWithdraw:
        rateUsd - (rateUsd * Number(configData?.FEE_WIDTHDRAW)) / 100,
      maxWithdraw: WITHDRAW_AMOUNT,
      farmVip,
      commissionRate,
      
    }).send(res);
  }),
};
